[versions]
# Core build
agp = "8.5.2"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
hilt = "2.51"

# AndroidX
coreKtx = "1.13.1"
appCompat = "1.7.0"
activityKtx = "1.9.2"

# UI
material = "1.13.0"
composeBom = "2024.10.00"

# Lifecycle & Coroutines
lifecycle = "2.8.4"
coroutines = "1.8.1"

# Networking
retrofit = "2.11.0"
okhttp = "4.12.0"
gson = "2.11.0"

# Java tooling (Hilt fix)
javapoet = "1.13.0"
glide = "4.16.0"


[libraries]
# AndroidX
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

# UI
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Lifecycle
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

# Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Networking
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Tooling
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
